fragment AuthorsParts on Authors {
  __typename
  authorId
  name
  avatar
  bio
}

fragment BlogParts on Blog {
  __typename
  title
  description
  authors
  date
  category
  isHeroBanner
  isFeatured
  isHotTopic
  heroImage
  heroImageCaption
  summary
  gallery {
    __typename
    image
    caption
  }
  body
}
